### ISSUE TITLE
Some files of the training set are wrong

### ISSUE THREAD

**Issue by Zhenxing-Dong** [liangs111/tensor_holography#10]
Hi,

When I extracted train_384_v2, the extractor told me that some files were damaged. Could you please upload train_384_v2 again?

Thank you very much!

**Comment by liangs111** [comment]
Hi Zhenxing, I re-upload the training dataset. Please let me know if that works. The exr images often break during compression. I recommend extracting them from the tfrecord, if you need individual frames.

**Comment by Zhenxing-Dong** [comment]
Hi! Thank you very much for your help.
